---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/innovx5x/aharam.in

    # Ensure folder exists
    - /bin/mkdir -p $DEPLOYPATH

    # Copy customer app to root (main site)
    - /bin/cp -R customer-app/. $DEPLOYPATH

    # Copy other apps (overwrite only these folders)
    - /bin/rm -rf $DEPLOYPATH/admin-panel
    - /bin/cp -R admin-panel $DEPLOYPATH

    - /bin/rm -rf $DEPLOYPATH/restaurant-panel
    - /bin/cp -R restaurant-panel $DEPLOYPATH

    - /bin/rm -rf $DEPLOYPATH/delivery-app
    - /bin/cp -R delivery-app $DEPLOYPATH

    - /bin/rm -rf $DEPLOYPATH/backend-api
    - /bin/cp -R backend-api $DEPLOYPATH
